"""empty message

Revision ID: 1b01bf1b8582
Revises: 940dab7837cd
Create Date: 2020-10-20 10:43:51.576731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b01bf1b8582'
down_revision = '940dab7837cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('player_two', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'offers', 'players', ['player_two'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_column('offers', 'player_two')
    # ### end Alembic commands ###
