"""empty message

Revision ID: 1c3ffdd57278
Revises: e2ec6528747c
Create Date: 2020-10-07 16:23:22.953104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3ffdd57278'
down_revision = 'e2ec6528747c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('time_limit', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('public', sa.Boolean(), nullable=True))
    op.add_column('offers', sa.Column('time_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'time_limit')
    op.drop_column('offers', 'public')
    op.drop_column('games', 'time_limit')
    # ### end Alembic commands ###
