"""empty message

Revision ID: 40de5c613eca
Revises: 
Create Date: 2020-09-29 14:45:08.275247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40de5c613eca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('winner', sa.Integer(), nullable=True))
    op.add_column('states', sa.Column('time_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'time_limit')
    op.drop_column('games', 'winner')
    # ### end Alembic commands ###
