"""empty message

Revision ID: 50b0dbf95f36
Revises: 5af90fe9656e
Create Date: 2020-10-20 12:29:28.880213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b0dbf95f36'
down_revision = '5af90fe9656e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('location', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('pick', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'pick')
    op.drop_column('players', 'location')
    # ### end Alembic commands ###
