"""empty message

Revision ID: 598626733784
Revises: 50b0dbf95f36
Create Date: 2020-10-21 14:41:03.091308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598626733784'
down_revision = '50b0dbf95f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('location', sa.String(length=50), nullable=True))
    op.add_column('players', sa.Column('pick', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'pick')
    op.drop_column('players', 'location')
    # ### end Alembic commands ###
