"""empty message

Revision ID: b32d76be83f8
Revises: 1c3ffdd57278
Create Date: 2020-10-20 10:22:51.579806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32d76be83f8'
down_revision = '1c3ffdd57278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('player_two', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'offers', 'players', ['player_two'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_column('offers', 'player_two')
    # ### end Alembic commands ###
