"""empty message

Revision ID: b9564ba77d8d
Revises: 5b5e9867227f
Create Date: 2020-10-22 11:57:46.568058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9564ba77d8d'
down_revision = '5b5e9867227f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('offer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'offers', ['offer_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'offer_id')
    # ### end Alembic commands ###
