"""empty message

Revision ID: e2ec6528747c
Revises: 40de5c613eca
Create Date: 2020-10-07 09:52:15.904366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ec6528747c'
down_revision = '40de5c613eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('time_limit', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('winner', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('public', sa.Boolean(), nullable=True))
    op.add_column('offers', sa.Column('time_limit', sa.Integer(), nullable=True))
    op.add_column('states', sa.Column('time_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'time_limit')
    op.drop_column('offers', 'time_limit')
    op.drop_column('offers', 'public')
    op.drop_column('games', 'winner')
    op.drop_column('games', 'time_limit')
    # ### end Alembic commands ###
